### ISSUE TITLE
Ranking instance types

### ISSUE THREAD

**Issue by rclark** [mapbox/price-pigeon#10]
I did some experimenting with ranking the instance types in the API response based on price per vcpu, memory, or storage space. Example of running the CLI command is:

```
》./bin/rank.js storage
type         price  vcpu  vcpuPrice  memory  memoryPrice  storageType  storage  storagePrice
-----------  -----  ----  ---------  ------  -----------  -----------  -------  ------------
i2.8xlarge   8.14   32    0.2544     244     0.0334       SSD          6400     0.0013      
i2.4xlarge   4.477  16    0.2798     122     0.0367       SSD          3200     0.0014      
i2.xlarge    1.12   4     0.28       30      0.0373       SSD          800      0.0014      
i2.2xlarge   2.239  8     0.2799     61      0.0367       SSD          1600     0.0014      
hi1.4xlarge  3.1    16    0.1938     60      0.0517       SSD          2048     0.0015 
... etc ...
```

Because the prices in the API response are on-demand, the results are predictable -- r3 instances are the best price point for memory, c3 for vcpu, d2/i2 for disk space. This might be more interesting though if it were mashed up with average price reductions for spot pricing (see #9).

Its also a lot of dimensions you might want to sort on. Aside from price per resource, you may only want SSD drives, or at least X memory, spot-price stability, etc. I think if I were going to actually turn my chicken-scratch code into a PR, I'd want to know more precisely how other people might like the interface to work.

cc @KaiBot3000

**Comment by KaiBot3000** [comment]
This is a neat way to visualize the api data! How are you imagining people will use this as part of price-pigeon?

**Comment by rclark** [comment]
It wouldn't really be part of the effort to create a mapping object for a CFN template, but just a general way to try and assess what instance types to choose for whatever you're up to.

**Comment by KaiBot3000** [comment]
Stale. Please re-open if needed!
