### ISSUE TITLE
support prices as percentages of the OnDemand price

### ISSUE THREAD

**Issue by jqtrde** [mapbox/price-pigeon#6]
First, this is fantastic 👏 🎉 

I'd love to use this with [@mapbox/pxm](https://github.com/mapbox/pxm/blob/13491fc95a28b0f55af385f12e42a54e01e2f60a/cloudformation/pxm.template.js#L190-L232). However, we run pxm on prices well below the OnDemand price currently output by price-pigeon. For example, the spot price for an `m3.xlarge` currently defined in PXM [is $0.07](https://github.com/mapbox/pxm/blob/13491fc95a28b0f55af385f12e42a54e01e2f60a/cloudformation/pxm.template.js#L205), while the price defined in `priceMap.json` [is $0.409](https://github.com/mapbox/price-pigeon/blob/131268b9f5b9b12fcb7110eb985a6e9969b60837/priceMap.json#L48).

Being able to do something like the following would be 👌 

> So if you want to bid at 90% of the ondemand price you can just plug in a 0.9 into this param.

Refs https://github.com/mapbox/pxm/issues/608.

**Comment by KaiBot3000** [comment]
I like this idea! I chatted with @yhahn a bit and have a gameplan for implementing this.

**Comment by jqtrde** [comment]
Closed via https://github.com/mapbox/price-pigeon/pull/7.
